name: Code test on PR

on:
  pull_request:
    branches: [master]
env:
  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GPG_KEY: ${{ secrets.GPG_KEY }}

jobs:
  test:
    runs-on: kroo-runners
    container:
      image: 711525892256.dkr.ecr.eu-west-1.amazonaws.com/b-social/docker-pipeline-builder
      options: --add-host host.docker.internal:host-gateway    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Test
        run: |
          . .github/workflows/setup-runner.sh
          start_docker
          ./go